# Generated by Django 2.2.9 on 2021-02-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210225_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['-priority', 'pub_date']},
        ),
    ]
