# Generated by Django 2.2.9 on 2021-02-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210225_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
