# Generated by Django 2.2.6 on 2021-03-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20210323_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='ваш текст', help_text='Напишите, что вы думаете по этой теме.', verbose_name='сообщение'),
        ),
    ]
