# Generated by Django 2.2.6 on 2021-04-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20210325_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Придумайте краткое и ёмкое название для группы сообщений', max_length=200, verbose_name='название группы'),
        ),
    ]
