# Generated by Django 2.2.6 on 2021-04-07 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0018_auto_20210406_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='ваш текст', help_text='Напишите, что вы думаете по этой теме.', verbose_name='комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='дата и время публикации комментария на сайте.', verbose_name='дата и время публикации')),
                ('author', models.ForeignKey(help_text='Пользователь оставивший комментарий.', on_delete=django.db.models.deletion.CASCADE, related_name='author_comment', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('post', models.ForeignKey(help_text='Сообщение.', on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='posts.Post', verbose_name='пост')),
            ],
        ),
    ]
