# Generated by Django 2.2.6 on 2021-04-08 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20210407_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'Комментарий'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'follow', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.AlterField(
            model_name='follow',
            name='author',
            field=models.ForeignKey(help_text='Пользователь, на которого подписываются.', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='пост'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, который подписывается.', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='post_comment',
        ),
        migrations.AlterModelTable(
            name='follow',
            table='follow_author',
        ),
    ]
